# Generated by Django 5.1.7 on 2025-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rasm',
            field=models.ImageField(blank=True, upload_to='rasmlar/'),
        ),
    ]
